version: '3'

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ex3_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ex3_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
