version: '1'
services:
  java-server:
    build: ./
    restart: always
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: work
    restart: always
    environment:
      POSTGRES_DB: ex3_2
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
